# Generated by Django 5.0.6 on 2024-10-17 02:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=255, verbose_name='customer_phone')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('pin_code', models.CharField(max_length=255, verbose_name='pin code')),
                ('building_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Building Type')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
                ('total_price', models.FloatField(verbose_name='total Price')),
                ('total_qty', models.IntegerField(verbose_name='Total Quantity')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='creation Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order_user', to='user.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
